# External variables:
# Package
#   The package to build and test. Defined in pipeline web ui because multiple pipelines use this YAML with different packages.
#   Example: @azure/event-hubs

jobs:
  - job: 'Test_Storage_Node'
    strategy:
      # Service Bus and Event Hubs currently lack support for running multiple test suites in parallel,
      # since the tests would attempt to use the same resources which causes conflicts.
      maxParallel: 1
      matrix:
        Linux_Node6X:
          OSName: 'Linux'
          OSVmImage: 'ubuntu-16.04'
          NodeVersion: '6.x'
        Linux_Node8X:
          OSName: 'Linux'
          OSVmImage: 'ubuntu-16.04'
          NodeVersion: '8.x'
        Linux_Node10X:
          OSName: 'Linux'
          OSVmImage: 'ubuntu-16.04'
          NodeVersion: '10.x'
        Windows_Node6X:
          OSName: 'Windows'
          OSVmImage: 'vs2017-win2016'
          NodeVersion: '6.x'
        Windows_Node8X:
          OSName: 'Windows'
          OSVmImage: 'vs2017-win2016'
          NodeVersion: '8.x'
        Windows_Node10X:
          OSName: 'Windows'
          OSVmImage: 'vs2017-win2016'
          NodeVersion: '10.x'
        Mac_Node6X:
          OSName: 'Mac'
          OSVmImage: 'macOS-10.13'
          NodeVersion: '6.x'
        Mac_Node8X:
          OSName: 'Mac'
          OSVmImage: 'macOS-10.13'
          NodeVersion: '8.x'
        Mac_Node10X:
          OSName: 'Mac'
          OSVmImage: 'macOS-10.13'
          NodeVersion: '10.x'

    pool:
      vmImage: '$(OSVmImage)'

    timeoutInMinutes: 240

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '$(NodeVersion)'
        displayName: 'Install Node.js $(NodeVersion)'

      - script: |
          node common/scripts/install-run-rush.js install
        displayName: 'rush install'

      - script: |
          node common/scripts/install-run-rush.js integration-test:node -t "$(Package)"
        displayName: 'rush integration-test:node -t "$(Package)"'
        env:
          # Storage
          ACCOUNT_NAME: $(js-storage-test-account-name)
          ACCOUNT_KEY: $(js-storage-test-account-key)
          ACCOUNT_SAS: $(js-storage-test-account-sas)

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-results.xml'
          testRunTitle: '$(OSName) Node $(NodeVersion) - Node'
        condition: succeededOrFailed()
        displayName: 'Publish node test results'

  - job: 'Test_Storage_Browser'
    strategy:
      # Service Bus and Event Hubs currently lack support for running multiple test suites in parallel,
      # since the tests would attempt to use the same resources which causes conflicts.
      maxParallel: 1
      matrix:
        Linux_Node10X:
          OSName: 'Linux'
          OSVmImage: 'ubuntu-16.04'
          NodeVersion: '10.x'
        Windows_Node10X:
          OSName: 'Windows'
          OSVmImage: 'vs2017-win2016'
          NodeVersion: '10.x'
        Mac_Node10X:
          OSName: 'Mac'
          OSVmImage: 'macOS-10.13'
          NodeVersion: '10.x'

    pool:
      vmImage: '$(OSVmImage)'

    timeoutInMinutes: 240

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '$(NodeVersion)'
        displayName: 'Install Node.js $(NodeVersion)'

      - script: |
          node common/scripts/install-run-rush.js install
        displayName: 'rush install'

      - script: |
          node common/scripts/install-run-rush.js integration-test:browser -t "$(Package)"
        condition: succeededOrFailed()
        displayName: 'rush integration-test:browser -t "$(Package)"'
        env:
          # Storage
          ACCOUNT_NAME: $(js-storage-test-account-name)
          ACCOUNT_KEY: $(js-storage-test-account-key)
          ACCOUNT_SAS: $(js-storage-test-account-sas)

      - task: PublishTestResults@2
        inputs:
          testRunner: JUnit
          testResultsFiles: "**/test-results.browser.xml"
          testRunTitle: '$(OSName) Node $(NodeVersion) - Browser'
        condition: succeededOrFailed()
        displayName: 'Publish browser test results'
